type=item
matchItems=iron_sword wooden_sword stone_sword diamond_sword golden_sword iron_axe wooden_axe stone_axe diamond_axe golden_axe netherite_sword netherite_axe wooden_hoe stone_hoe iron_hoe golden_hoe diamond_hoe netherite_hoe
nbt.display.Name=iregex:iron hay sickle
model=./iron_hay_sickle